
- name: "Flush handlers"
  meta: flush_handlers

- name: Changing hostname for the inventory_hostname
  hostname:
    name:  "{{ inventory_hostname }}"
    use: systemd
  when: changing_hostname


- name: Include install_consul.yml tasks
  include_tasks:
    file: install_consul.yml 
  
- name: Include consul-services.yml tasks
  include_tasks:
    file: consul-services.yml 
