---
- name: Converge
  hosts: all
  vars:
    - ansible_remote_tmp: "/tmp/"
  tasks:
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: "Install classic libs"
      package:
        name:
          - unzip
          - iproute2
          - python3-pip

