name: Run molecule test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        
      - name: Run Molecule
        uses: gofrolist/molecule-action@v2.3.2
        with: 
          molecule_options: converge

